name: CI

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      # TODO: укажите шаги по:
      # 1. Установке зависимостей
      - uses: actions/upload-artifact@v4
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm install
      - run: npm run build --if-present
      #- run: npm test

      # - uses: actions/checkout@v4
      # - name: Use Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "20.x"
      # - name: Install dependencies
      #   run: npm ci
      # # 2. Сборке проекта
      # - name: Upload Artifact
      #   uses: actions/upload-pages-artifact@v1
      #   with:
      #     path: build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
