name: CI

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      # TODO: укажите шаги по:
      # 1. Установке зависимостей
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm install
      - run: npm run build --if-present
      #- run: npm test

      # - uses: actions/checkout@v4
      # - name: Use Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "20.x"
      # - name: Install dependencies
      #   run: npm ci
      # # 2. Сборке проекта
      # - name: Upload Artifact
      #   uses: actions/upload-pages-artifact@v1
      #   with:
      #     path: build
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
